<?php
error_reporting(E_ALL); ini_set('display_errors',1);
require_once __DIR__ . '/../app/config/database.php';
$pdo=Database::connect(); $message='';
$positions=['HR','IT support','DA','Reservation','Recruiter','Manager'];
$referenceTypes=['Company old employee','Walking','Other'];
if ($_SERVER['REQUEST_METHOD']==='POST') {
  $appNo='APP-'.date('Ymd').'-'.mt_rand(1000,9999);
  $stmt=$pdo->prepare("INSERT INTO candidates (application_no, full_name, email, phone, position_applied, address, total_experience, source_type, source_reference_name, current_status, applied_at) VALUES (?,?,?,?,?,?,?,?,?,'submitted',NOW())");
  $stmt->execute([$appNo, trim($_POST['full_name'] ?? ''), trim($_POST['email'] ?? ''), trim($_POST['phone'] ?? ''), trim($_POST['position_applied'] ?? ''), trim($_POST['address'] ?? ''), (float)($_POST['total_experience'] ?? 0), trim($_POST['reference_type'] ?? ''), trim($_POST['reference_name'] ?? '')]);
  $candidateId=(int)$pdo->lastInsertId();
  $uploadRoot=__DIR__ . '/uploads'; if(!is_dir($uploadRoot.'/resumes')) mkdir($uploadRoot.'/resumes',0777,true); if(!is_dir($uploadRoot.'/photos')) mkdir($uploadRoot.'/photos',0777,true);
  if (!empty($_FILES['resume']['name']) && $_FILES['resume']['error']===UPLOAD_ERR_OK) { $name=time().'_resume_'.preg_replace('/[^a-zA-Z0-9._-]/','_',$_FILES['resume']['name']); move_uploaded_file($_FILES['resume']['tmp_name'],$uploadRoot.'/resumes/'.$name); $pdo->prepare("INSERT INTO candidate_documents (candidate_id, document_type, original_file_name, file_path) VALUES (?, 'resume', ?, ?)")->execute([$candidateId,$_FILES['resume']['name'],'uploads/resumes/'.$name]); }
  if (!empty($_FILES['photo']['name']) && $_FILES['photo']['error']===UPLOAD_ERR_OK) { $name=time().'_photo_'.preg_replace('/[^a-zA-Z0-9._-]/','_',$_FILES['photo']['name']); move_uploaded_file($_FILES['photo']['tmp_name'],$uploadRoot.'/photos/'.$name); $pdo->prepare("INSERT INTO candidate_documents (candidate_id, document_type, original_file_name, file_path) VALUES (?, 'photo', ?, ?)")->execute([$candidateId,$_FILES['photo']['name'],'uploads/photos/'.$name]); }
  $pdo->prepare("INSERT INTO candidate_status_logs (candidate_id, round_id, action_by, action_role, old_status, new_status, note) VALUES (?, NULL, NULL, 'candidate', 'new', 'submitted', 'Application submitted')")->execute([$candidateId]);
  $message='Application submitted successfully. Application number: '.$appNo;
}
$title='Apply'; include __DIR__ . '/../app/views/layouts/header.php'; ?>
<div class="form-page grid grid-2 apply-grid"><section class="card intro-card"><span class="eyebrow">UNIRE Careers</span><h2>Candidate Application Form</h2><p>Fill your details, upload resume and passport-size photo, and submit for recruiter review.</p><?php if($message): ?><div class="notice success"><?= h($message) ?></div><?php endif; ?></section><section class="card"><form method="post" enctype="multipart/form-data"><div class="form-group"><label>Full Name</label><input type="text" name="full_name" required></div><div class="grid grid-2"><div class="form-group"><label>Email</label><input type="email" name="email" required></div><div class="form-group"><label>Phone</label><input type="text" name="phone" required></div></div><div class="grid grid-2"><div class="form-group"><label>Apply Position</label><select name="position_applied" required><option value="">Select position</option><?php foreach($positions as $p): ?><option value="<?= h($p) ?>"><?= h($p) ?></option><?php endforeach; ?></select></div><div class="form-group"><label>Total Experience</label><input type="number" step="0.1" name="total_experience"></div></div><div class="form-group"><label>Address</label><textarea name="address" rows="3"></textarea></div><div class="grid grid-2"><div class="form-group"><label>Reference</label><select name="reference_type"><option value="">Select reference</option><?php foreach($referenceTypes as $r): ?><option value="<?= h($r) ?>"><?= h($r) ?></option><?php endforeach; ?></select></div><div class="form-group"><label>Reference Name / Other</label><input type="text" name="reference_name" placeholder="Employee name or manual reference"></div></div><div class="grid grid-2"><div class="form-group"><label>Resume</label><input type="file" name="resume" accept=".pdf,.doc,.docx" required></div><div class="form-group"><label>Passport-size Photo</label><input type="file" name="photo" accept="image/*"></div></div><button class="btn" type="submit">Submit Application</button></form></section></div>
<?php include __DIR__ . '/../app/views/layouts/footer.php'; ?>
