<?php
error_reporting(E_ALL); ini_set('display_errors',1);
require_once __DIR__ . '/../app/helpers/auth.php'; require_once __DIR__ . '/../app/config/database.php'; require_role('admin');
$pdo=Database::connect(); $status=trim($_GET['status'] ?? ''); $where=''; $params=[]; if($status!==''){ $where=' WHERE c.current_status = ? '; $params[]=$status; }
$sql="SELECT c.application_no, c.full_name, c.email, c.phone, c.position_applied, c.current_status, c.final_decision,(SELECT recommendation FROM interview_feedback f WHERE f.candidate_id=c.id ORDER BY f.id DESC LIMIT 1) AS latest_feedback,(SELECT remark_text FROM interview_feedback f WHERE f.candidate_id=c.id ORDER BY f.id DESC LIMIT 1) AS feedback_note,(SELECT note FROM candidate_status_logs l WHERE l.candidate_id=c.id AND l.new_status IN ('rejected','rejected_without_interview') ORDER BY l.id DESC LIMIT 1) AS rejection_reason FROM candidates c $where ORDER BY c.id DESC";
$stmt=$pdo->prepare($sql); $stmt->execute($params); $rows=$stmt->fetchAll(PDO::FETCH_ASSOC);
if(isset($_GET['export']) && $_GET['export']==='csv'){ header('Content-Type: text/csv'); header('Content-Disposition: attachment; filename="candidate-report.csv"'); $out=fopen('php://output','w'); fputcsv($out,['application_no','full_name','email','phone','position_applied','current_status','final_decision','latest_feedback','feedback_note','rejection_reason']); foreach($rows as $r){ fputcsv($out,$r); } fclose($out); exit; }
$title='Reports'; include __DIR__ . '/../app/views/layouts/header.php'; ?>
<div class="section-title"><h2>Admin Reports</h2><div class="actions"><a class="btn" href="reports.php?<?= http_build_query(array_filter(['status'=>$status,'export'=>'csv'])) ?>">Export CSV</a></div></div><div class="card report-filter"><form method="get" class="inline-form"><div class="form-group"><label>Status Filter</label><select name="status"><option value="">All</option><option value="selected" <?= $status==='selected'?'selected':'' ?>>Selected</option><option value="rejected" <?= $status==='rejected'?'selected':'' ?>>Rejected</option><option value="rejected_without_interview" <?= $status==='rejected_without_interview'?'selected':'' ?>>Rejected without interview</option><option value="sent_to_manager" <?= $status==='sent_to_manager'?'selected':'' ?>>Sent to manager</option></select></div><button class="btn btn-outline" type="submit">Filter</button></form></div><div class="card"><table><thead><tr><th>App No</th><th>Name</th><th>Position</th><th>Status</th><th>Feedback</th><th>Reject Reason</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><?= h($r['application_no']) ?></td><td><?= h($r['full_name']) ?></td><td><?= h($r['position_applied']) ?></td><td><?= h($r['current_status']) ?></td><td><?= h(($r['latest_feedback'] ?: '-') . ' / ' . ($r['feedback_note'] ?: '-')) ?></td><td><?= h($r['rejection_reason'] ?: '-') ?></td></tr><?php endforeach; ?></tbody></table></div>
<?php include __DIR__ . '/../app/views/layouts/footer.php'; ?>
