<?php
error_reporting(E_ALL); ini_set('display_errors',1);
require_once __DIR__ . '/../app/helpers/auth.php'; require_once __DIR__ . '/../app/config/database.php'; require_role('admin');
$pdo=Database::connect(); $message=''; $roles=$pdo->query("SELECT * FROM roles ORDER BY id")->fetchAll(PDO::FETCH_ASSOC);
if($_SERVER['REQUEST_METHOD']==='POST'){
  $action=$_POST['action'] ?? '';
  if($action==='create_user'){ $pdo->prepare("INSERT INTO users (full_name,email,phone,password_hash,status,password_changed_at) VALUES (?,?,?,?, 'active', NOW())")->execute([trim($_POST['full_name']),trim($_POST['email']),trim($_POST['phone']),password_hash($_POST['password'], PASSWORD_DEFAULT)]); $uid=(int)$pdo->lastInsertId(); $pdo->prepare("INSERT INTO user_roles (user_id, role_id) VALUES (?,?)")->execute([$uid,(int)$_POST['role_id']]); $message='User created'; }
  elseif($action==='delete_user'){ $id=(int)$_POST['id']; if($id !== (int)current_user()['id']){ $pdo->prepare("DELETE FROM user_roles WHERE user_id=?")->execute([$id]); $pdo->prepare("DELETE FROM users WHERE id=?")->execute([$id]); $message='User deleted'; } }
  elseif($action==='reset_password'){ $id=(int)$_POST['id']; $newPassword=trim($_POST['new_password']); if($id>0 && $newPassword!==''){ $pdo->prepare("UPDATE users SET password_hash=?, password_changed_at=NOW() WHERE id=?")->execute([password_hash($newPassword, PASSWORD_DEFAULT),$id]); $message='Password reset done'; } }
}
$users=$pdo->query("SELECT u.*, r.name AS role_name FROM users u LEFT JOIN user_roles ur ON ur.user_id=u.id LEFT JOIN roles r ON r.id=ur.role_id ORDER BY u.id DESC")->fetchAll(PDO::FETCH_ASSOC);
$title='Users'; include __DIR__ . '/../app/views/layouts/header.php'; ?>
<?php if($message): ?><div class="notice success"><?= h($message) ?></div><?php endif; ?><div class="grid grid-2"><div class="card"><div class="section-title"><h2>Create User</h2><span class="pill">Password expires in 30 days</span></div><form method="post"><input type="hidden" name="action" value="create_user"><div class="form-group"><label>Name</label><input name="full_name" required></div><div class="form-group"><label>Email</label><input name="email" type="email"></div><div class="form-group"><label>Phone</label><input name="phone"></div><div class="grid grid-2"><div class="form-group"><label>Password</label><input name="password" required></div><div class="form-group"><label>Role</label><select name="role_id"><?php foreach($roles as $role): ?><option value="<?= (int)$role['id'] ?>"><?= h($role['name']) ?></option><?php endforeach; ?></select></div></div><button class="btn" type="submit">Add User</button></form></div><div class="card"><div class="section-title"><h2>Manage Users</h2><span class="pill"><?= count($users) ?> users</span></div><table><thead><tr><th>Name</th><th>Role</th><th>Email</th><th>Password Changed</th><th>Actions</th></tr></thead><tbody><?php foreach($users as $u): ?><tr><td><?= h($u['full_name']) ?></td><td><?= h($u['role_name']) ?></td><td><?= h($u['email']) ?></td><td><?= h($u['password_changed_at'] ?: '-') ?></td><td><form method="post" class="table-actions"><input type="hidden" name="id" value="<?= (int)$u['id'] ?>"><input type="text" name="new_password" placeholder="new password"><button class="btn btn-outline" name="action" value="reset_password">Reset</button><?php if((int)$u['id'] !== (int)current_user()['id']): ?><button class="btn btn-danger" name="action" value="delete_user" onclick="return confirm('Delete user?')">Delete</button><?php endif; ?></form></td></tr><?php endforeach; ?></tbody></table></div></div>
<?php include __DIR__ . '/../app/views/layouts/footer.php'; ?>
